application: cssfilters
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /videos
  static_dir: videos

- url: .*
  script: main.py

libraries:
- name: webapp2
  version: "2.5.1"
